"""user_id

Revision ID: 051e69822238
Revises: 5f9ad28ad946
Create Date: 2025-03-15 14:59:31.952661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '051e69822238'
down_revision: Union[str, None] = '5f9ad28ad946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculation_sets', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'calculation_sets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calculation_sets', type_='foreignkey')
    op.drop_column('calculation_sets', 'user_id')
    # ### end Alembic commands ###
