"""calculation file_hash info FK

Revision ID: 5a4ac02353e0
Revises: 5dc0ca5d3eda
Create Date: 2025-03-22 21:04:03.281488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a4ac02353e0'
down_revision: Union[str, None] = '5dc0ca5d3eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'calculations', 'molecule_set_stats', ['file_hash'], ['file_hash'])
    op.drop_column('calculations', 'info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculations', sa.Column('info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'calculations', type_='foreignkey')
    # ### end Alembic commands ###
