"""molecule_set_stats

Revision ID: 5dc0ca5d3eda
Revises: 9430c1cdba08
Create Date: 2025-03-20 18:25:00.246763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc0ca5d3eda'
down_revision: Union[str, None] = '9430c1cdba08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('molecule_set_stats',
    sa.Column('file_hash', sa.VARCHAR(length=100), nullable=False),
    sa.Column('total_molecules', sa.Integer(), nullable=False),
    sa.Column('total_atoms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('file_hash')
    )
    op.create_table('atom_type_counts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('molecule_set_id', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['molecule_set_id'], ['molecule_set_stats.file_hash'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atom_type_counts')
    op.drop_table('molecule_set_stats')
    # ### end Alembic commands ###
