"""init

Revision ID: 7e6575e75273
Revises: 
Create Date: 2025-03-12 22:21:56.661882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e6575e75273'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation_sets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calculation_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.VARCHAR(length=20), nullable=False),
    sa.Column('parameters', sa.VARCHAR(length=50), nullable=True),
    sa.Column('read_hetatm', sa.Boolean(), nullable=False),
    sa.Column('ignore_water', sa.Boolean(), nullable=False),
    sa.Column('permissive_types', sa.Boolean(), nullable=False),
    sa.Column('set_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['calculation_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calculations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file', sa.VARCHAR(length=100), nullable=False),
    sa.Column('file_hash', sa.VARCHAR(length=100), nullable=False),
    sa.Column('info', sa.JSON(), nullable=False),
    sa.Column('charges', sa.JSON(), nullable=False),
    sa.Column('set_id', sa.Uuid(), nullable=False),
    sa.Column('config_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['calculation_configs.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['calculation_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculations')
    op.drop_table('calculation_configs')
    op.drop_table('calculation_sets')
    # ### end Alembic commands ###
