"""CalculationSetStats file_name

Revision ID: aa87655da208
Revises: b55dbc463b4a
Create Date: 2025-04-20 10:53:30.659946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa87655da208'
down_revision: Union[str, None] = 'b55dbc463b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'calculation_set_configs', ['calculation_set_id', 'config_id'])
    op.add_column('calculation_set_stats', sa.Column('file_name', sa.VARCHAR(length=255), nullable=True))
    op.create_unique_constraint(None, 'calculation_set_stats', ['calculation_set_id', 'molecule_set_id'])
    op.alter_column('calculations', 'file_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calculations', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint(None, 'calculation_set_stats', type_='unique')
    op.drop_column('calculation_set_stats', 'file_name')
    op.drop_constraint(None, 'calculation_set_configs', type_='unique')
    # ### end Alembic commands ###
