CONFIG_FILE = '/etc/ACC2.conf'
PARAMETERS_DIRECTORY = '/home/charge/chargefw2/share/parameters'
CHARGEFW2_DIR = '/home/charge/chargefw2'
EXAMPLES_DIR = '/home/charge/www/ACC2/examples'
LOG_DIR = '/home/charge/logs'
